In [1]:
import numpy as np

In [24]:
arr = np.array([[1, 2], [3, 4]])

print('arr[0][0]: ', arr[0][0], '\narr[1,1]: ', arr[1,1])
#print('arr[0][1]: ', arr[0][1], '\narr[1,0]:', arr[1][0])
arr.shape

arr[0][0]:  1 
arr[1,1]:  4


(2, 2)

In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr.shape

(4, 2)

In [25]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[0, 1], [2, 3]])
arr1 + arr2

array([[1, 3],
       [5, 7]])

In [26]:
arr1 + 1

array([[2, 3],
       [4, 5]])

In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[0, 1], [2, 3]])

arr1 * arr2

array([[ 0,  2],
       [ 6, 12]])

In [28]:
np.matmul(arr1, arr2) ## matrix 곱셈

array([[ 4,  7],
       [ 8, 15]])

In [29]:
np.arange(10) ## 배열 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.zeros((3, 2, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [32]:
print('shape: ', arr.shape, '\narr:\n', arr) # arr 배열의 모양과 내용 출력

shape:  (2, 2) 
arr:
 [[1 2]
 [3 4]]


In [33]:
print('shape: ', arr.shape, '\narr:\n', arr.reshape(1,4)) # arr 배열의 모양을 (1, 4) 로 변경

shape:  (2, 2) 
arr:
 [[1 2 3 4]]


In [34]:
# Create vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [35]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [38]:
vector.shape

(6,)

In [39]:
matrix.shape

(3, 3)

In [40]:
# Tranpose vector
vector.T

array([1, 2, 3, 4, 5, 6])

In [41]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [43]:
# Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [44]:
# Calculate the trace of the matrix
matrix.diagonal().sum()

15